# Generated by Django 3.2.4 on 2021-06-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authead', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
